### ISSUE TITLE
No META.json File

### ISSUE THREAD

**Issue by shlomif** [bricas/dbix-class-datetime-epoch#5]
Hi!

I was assigned this distro for the CPAN http://cpan-prc.org/ for September. It noted that it didn't have a META.json file and this is due to its use of https://metacpan.org/pod/release/ETHER/Module-Install-1.18/lib/Module/Install.pm which is now discouraged. Can I convert this distribution to Dist-Zilla or similar to fix this and other problems?

**Comment by bricas** [comment]
Sure, have at 'er!

**Comment by shlomif** [comment]
On Wed, 06 Sep 2017 00:28:05 +0000 (UTC)
Brian Cassidy <notifications@github.com> wrote:

> Sure, have at 'er!
> 

Thanks Brian! I could not be too sure because the maints of some other CPAN
distros here on github did not approve of the transition away from M-I.

Regards,

Shlomi

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://youtu.be/n6KAGqjdmsk - “Hurt Me Tomorrow”

If a tree falls down in the middle of the forest, and there's nobody in its
vicinity, it will still make a sound, because Chuck Norris can hear it.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
